# Generated by Django 4.1.2 on 2024-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AminoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.FloatField()),
                ('init_amino', models.CharField(max_length=100)),
                ('current_formy_type', models.CharField(max_length=100)),
                ('current_ion_type', models.CharField(max_length=100)),
                ('input_aminos', models.JSONField()),
            ],
        ),
    ]
